<?php
$db['default']['hostname']="nosieto.mysql.ukraine.com.ua";
$db['default']['username']="nosieto_db";
$db['default']['password']="8GT3x5gm";
$db['default']['database']="nosieto_db";
$db['default']['dbdriver']="mysql";
$db['default']['dbprefix']="";
$db['default']['pconnect']=true;
$db['default']['db_debug']=0;
$db['default']['cache_on']=false;
$db['default']['cachedir']="";
$db['default']['char_set']="utf8";
$db['default']['dbcollat']="utf8_general_ci";
$db['default']['swap_pre']="";
$db['default']['autoinit']=true;
$db['default']['stricton']=false;
$config['base_url']="";
$config['index_page']="";
$config['uri_protocol']="AUTO";
$config['url_suffix']="";
$config['language']="russian";
$config['charset']="UTF-8";
$config['enable_hooks']=false;
$config['subclass_prefix']="MY_";
$config['permitted_uri_chars']="a-z 0-9~%.:_-";
$config['allow_get_array']=true;
$config['enable_query_strings']=false;
$config['controller_trigger']="c";
$config['function_trigger']="m";
$config['directory_trigger']="d";
$config['log_threshold']=0;
$config['log_path']="";
$config['log_date_format']="Y-m-d H:i:s";
$config['cache_path']="";
$config['encryption_key']="kna6a2k2m)@#0x23273x2g";
$config['sess_cookie_name']="ci_session";
$config['sess_expiration']=86400;
$config['sess_expire_on_close']=false;
$config['sess_encrypt_cookie']=false;
$config['sess_use_database']=false;
$config['sess_table_name']="ci_sessions";
$config['sess_match_ip']=false;
$config['sess_match_useragent']=false;
$config['sess_time_to_update']=300;
$config['cookie_prefix']="";
$config['cookie_domain']="";
$config['cookie_path']="/";
$config['cookie_secure']=false;
$config['global_xss_filtering']=false;
$config['csrf_protection']=false;
$config['csrf_token_name']="csrf_test_name";
$config['csrf_cookie_name']="csrf_cookie_name";
$config['csrf_expire']=7200;
$config['compress_output']=false;
$config['time_reference']="local";
$config['rewrite_short_tags']=false;
$config['proxy_ips']="";
$config['robots_txt_content']="";
$config['template_bottom_scripts']="";
$config['template_favicon']="favicon.ico";
$config['site_default_title']="mebel-prosto.kiev.ua";
$config['site_default_meta_title']="";
$config['site_default_meta_keywords']="";
$config['site_default_meta_description']="";
$config['site_disabled']=0;
$config['site_disabled_text']="";
$config['version']="1.0";
$config['email_from']="noreply@mebel-prosto.kiev.ua";
$config['email_from_name']="mebel-prosto.kiev.ua";
$config['mod_content_main_picture_options']="";
$config['mod_content_category_main_picture_options']="";
$config['mod_media_video_picture_options']="";
$config['mod_media_photo_picture_options']="resize(new_image:uploads/media/big/%IMAGE_NAME%,maxWidth:800);
square(new_image:uploads/media/thumbs/%IMAGE_NAME%,size:280);";
$config['404_page_menu_id']=24;
$mod_shop['images_options']="resize(new_image:uploads/shop/products/big/%IMAGE_NAME%, maxWidth:800);

resize(new_image:uploads/shop/products/thumbs/%IMAGE_NAME%, maxWidth:336);

resize(new_image:uploads/shop/products/thumbs2/%IMAGE_NAME%, maxWidth:446);

crop(new_image:uploads/shop/products/thumbs3/%IMAGE_NAME%,size:103x103);

crop(new_image:uploads/shop/products/thumbs4/%IMAGE_NAME%,size:182x182);";
$mod_shop['categories_images_options']="";
$mod_shop['manufacturers_images_options']="";
$config['calc']['kitchen']=100;
$config['calc']['cabinet']=100;
?>