<?php
$config['pg']['full_tag_open'] = "<ul class='pagination  pagination-sm'>";
$config['pg']['full_tag_close'] ="</ul>";
$config['pg']['num_tag_open'] = '<li>';
$config['pg']['num_tag_close'] = '</li>';
$config['pg']['cur_tag_open'] = "<li class='disabled'><li class='active'><a href='#'>";
$config['pg']['cur_tag_close'] = "<span class='sr-only'></span></a></li>";
$config['pg']['next_tag_open'] = "<li>";
$config['pg']['next_tagl_close'] = "</li>";
$config['pg']['prev_tag_open'] = "<li>";
$config['pg']['prev_tagl_close'] = "</li>";
$config['pg']['first_tag_open'] = "<li>";
$config['pg']['first_tagl_close'] = "</li>";
$config['pg']['last_tag_open'] = "<li>";
$config['pg']['last_tagl_close'] = "</li>";
$config['pg']['page_query_string'] = true;
$config['pg']['query_string_segment'] = 'pg';
$config['pg']['use_page_numbers'] = true;
$config['pg']['first_link'] = '<span class="glyphicon glyphicon-step-backward sic-rel" aria-hidden="true"></span>';
$config['pg']['last_link'] = '<span class="glyphicon glyphicon-step-forward sic-rel" aria-hidden="true"></span>';
$config['pg']['next_link'] = '<span class="glyphicon glyphicon-triangle-right sic-rel" aria-hidden="true"></span>';
$config['pg']['prev_link'] = '<span class="glyphicon glyphicon-triangle-left sic-rel" aria-hidden="true"></span>';
$config['pg']['num_links'] = 1;